### ISSUE TITLE
Incorporating Marvel and DC Comic sources?

### ISSUE THREAD

**Issue by manu-smpx** [aplanas/kmanga#3]
I am trying to incorporate Marvel and DC Comics sources into the code, but am unable to understand some parts, can anyone look into it? I am a not very versed in python.

**Comment by aplanas** [comment]
I can help you with the code, but not sure that is a good idea. As today kindle is a black and white eink screen. Manga in very adequate because of that, but USA comics are with colors.

Anyway, the first step is to find a source, like for example https://digitalcomicmuseum.com/. And now we need to create an spider that recover the data. That it is all : )

**Comment by aplanas** [comment]
But if you have a list of sources that you consider interesting, I can try to help to add them

**Comment by aplanas** [comment]
Meanwhile, because kmanga is about manga, I am going to close this issue. If you miss a source, or you want to revisit this, feel free to open a new issue.

**Comment by manu-smpx** [comment]
Sure. I was busy with other projects and searching for sources went to a second priority. I'll update this comment if/when I find a reliable source for comics. Or maybe I'll fork the repository for a similar website for comics. I hope that will be fine with you,
